### PR TITLE
Eway Improvements to support transparent redirect & shared gateway recurring

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
The interface allows for calling functions to check whether the gateway is transparentRedirect.

We should respect that here

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
I don't think the CI error relates to the change

**Comment by delatbabel** [comment]
The CI errors are because your block in RapidDirectAbstractRequest commencing with:

    if (!$this->getCardReference()) {

... is indented incorrectly.  You have indented with 2 spaces, you need 4 for CS compliance.

**Comment by eileenmcnaughton** [comment]
Thanks for that - I've fixed those - the original 5.3 CI error stands.

With these changes I have almost gotten eway working as recurring across all 3 Rapid methods - only one thing is still catching me (I hope only one) - the only way to set it process recurring without a cvn is to use the RapidDirect interface. I don't want my code to have to be aware of that so I logged https://github.com/thephpleague/omnipay-common/issues/160 in order to get some thoughts on a generic way to define that. Note that the gateway would also need to call Direct rather than Shared/Transparent method. Resolving that is not a blocker to these changes.

**Comment by delatbabel** [comment]
You can remove 5.3 from the travis.yml file, we're no longer seeing anyone use that. Most gateways have moved away from it.

**Comment by eileenmcnaughton** [comment]
Done! Yay - it passes!

**Comment by JeramyNS** [comment]
Any update on this?
I needed to get tokens working in transparent redirects.

Before I saw this I started working on doing my own implementation.
https://github.com/JeramyNS/omnipay-eway
I could probably simply it to only need one function like setMethod('tokenPayment") and store it as a parameter. However I'm guessing this approach is probably better.

**Comment by eileenmcnaughton** [comment]
This was working for me - it adds a separate gateway rather than a transparent redirect option to an existing gateway (which is kinda important when integrating into a package that supports multiple gateways)

**Comment by JeramyNS** [comment]
@eileenmcnaughton awesome!
@delatbabel can we please get this pull request merged?

**Comment by JeramyNS** [comment]
Actually, I still don't see anything in there for doing the method TokenPayment?
So you can take a payment and create a token at the same time

**Comment by eileenmcnaughton** [comment]
You can purchase and create a token at the same time - or you can use createCard - https://omnipay.thephpleague.com/api/token-billing/

**Comment by fryiee** [comment]
What's the situation on  this? Would love to get it implemented...

**Comment by JeramyNS** [comment]
@fryiee same. I ended up hacking together to get what I wanted but I'd prefer to use this.

**Comment by delatbabel** [comment]
Merged, thanks. I have been unwell for some time and I'm slowly getting around to my github backlog. Please confirm that this works in production then I will tag for release.

**Comment by fryiee** [comment]
@delatbabel thanks!

**Pull request merged**
