### PR TITLE
Add eWAY Rapid Direct Connection

### PR DESCRIPTION
**Pull request by incarnate**
This pull request adds the final eWAY Rapid API, [Direct Connection](https://eway.io/api-v3/#direct-connection). It includes purchase, authorise, capture and create/update card. Full unit test coverage and documentation is also present.

eWAY's Rapid Direct replaces the older Direct XML API which is implemented in the "Eway_Direct" gateway (at this stage I've just left a note in that class).

### CODE REVIEW

**Comment by alexw23** [comment]
Looking good - does this support client side encryption on the card number?

**Comment by incarnate** [comment]
Hi Alex, thanks! Your eWAY Direct integration is great, but obviously we'd love everyone to get all the features of Rapid.

Yes this does work with [client side encryption](https://eway.io/api-v3/#client-side-encryption), although I had to add some extra fields to the request for it since the CreditCard object won't accept the encrypted card number. 

A brief example with the encrypted card data is as follows:

    // Do a purchase transaction on the gateway
    $request = $gateway->purchase(array(
        'amount'            => '10.00',
        'currency'          => 'AUD',
        'transactionType'   => 'Purchase',
        'card'              => $card,
        'encryptedCardNumber' => 'eCrypted:YVe4GMLMSxF5m1nixtBvVlmaLDgjI+ZYM5GHuX1XjlbRTnhe==',
        'encryptedCardCvv' => 'eCrypted:ZvEfRd1DHwJ7dYV59DZqoaCFujvK+26VKS9Tp3uGp5kVki8CH=='
    ));

Name & expiry still get passed the usual way.

**Comment by alexw23** [comment]
Looks good, How does $card work without the card number however?

**Comment by incarnate** [comment]
CreditCard is fine as long as you don't call validate() - which shouldn't be called from outside Omnipay anyway

**Comment by alexw23** [comment]
Does the client side encryption work for Create and Update Card methods? 

Also do you need to send `transactionType` (see your code above) it seems like could be in the PurchaseRequest code?

**Comment by incarnate** [comment]
Create and update should support the client side encryption fields, yes.

`transactionType` is handled in the [AbstractRequest](https://github.com/incarnate/omnipay-eway/blob/eway_rapid_direct/src/Message/AbstractRequest.php) class (along with various other Rapid fields such as CustomerIP and Items), and does indeed default to purchase :-)

**Comment by incarnate** [comment]
Hi @kayladnls - have you had some time to review this PR?

**Comment by incarnate** [comment]
Thanks @kayladnls !

**Pull request merged**
