### PR TITLE
Shared token requests

### PR DESCRIPTION
**Pull request by fryiee**
Added Requests for both CreateCard and UpdateCard through RapidShared (roughly mimicking the functionality in RapidDirect). I have not added any response requests as you can utilise the `completePurchase()` method to finalise both of them all the same. Let me know if you would prefer these as separate responses.

### CODE REVIEW

**Comment by incarnate** [comment]
Thanks for the PR, looks good! 

Only change you might want to consider is extending `RapidSharedPurchaseRequest` for the two requests to cut down on code duplication - just override `getData`. See [RapidDirectCreateCardRequest](https://github.com/thephpleague/omnipay-eway/blob/master/src/Message/RapidDirectCreateCardRequest.php) as an example

**Comment by fryiee** [comment]
I have just pushed up another commit which makes them extend rather than duplicate code. Thanks!

**Comment by incarnate** [comment]
Much neater, thanks!
@delatbabel please consider for merging

**Comment by fryiee** [comment]
Is this likely to be merged? I just need to know if I need to attach my fork to my composer package instead of the mainline gateway as I need to roll out this module this week.

**Comment by incarnate** [comment]
This should be fine to be merged, however since omnipay is an open source project the maintainers are all volunteers and things don't always happen quickly. 

If you need to release this week I'd say roll with your own fork and you can update to official once the merge has happened.

**Comment by delatbabel** [comment]
Hi, yes I saw the ping and I have looked at the code briefly. It should be OK to merge, but I need to have a deeper read and I have a backlog of paying job tasks at the moment. So I'll try to get this done in the next few days.

**Comment by fryiee** [comment]
No problems guys, fully understand and thanks for your responses. I'm running from my fork for now.

**Comment by delatbabel** [comment]
OK merged, thanks.  Sorry for the delay and thanks for your patience. If you can confirm that this works in a production environment then I will tag for release.

**Comment by fryiee** [comment]
@delatbabel I never responded to this. I've been using my fork in production for a little while now.

**Comment by fryiee** [comment]
Hi @delatbabel I'm working on another project that is in need of this. Do you know if it's possible to get this tagged for release? At the moment we're going to run our tagged fork but it would be nice to use the mainline package.

**Comment by delatbabel** [comment]
Released as 2.2.2

**Comment by fryiee** [comment]
@delatbabel thanks a bunch!

**Pull request merged**
