### PR TITLE
Add required redirect data

### PR DESCRIPTION
**Pull request by JeramyNS**
- Fixes compatibly for eWay's Transparent Redirect

### CODE REVIEW

**Comment by JeramyNS** [comment]
I had some issues trying to implement eWays Transparent Redirect. Turns out that it was missing some required parameters. 
I don't think this has changed in a long time so I'm surprised that there has been no issue reports, unless I'm missing something?

**Comment by JeramyNS** [comment]
Hmm, guess there are times this gets called where the card isn't set. Perhaps it might needs some tweaks.
Don't have time to look at it now and might not get time for a little while.
For the moment this fixes my problem at least.

**Comment by incarnate** [comment]
Thanks for the PR Jeramy! 
The intention of `getRedirectData()` is to return the data sent from eWAY needed for the Transparent Redirect function. The card data should be entered by the user and submitted directly to eWAY (using the URL from `getRedirectUrl()`).

If the card data is in this function then it is on the server, which means a higher level of PCI requirements which Transparent Redirect was designed to avoid.

Hope that makes sense!

**Comment by JeramyNS** [comment]
That makes a lot of sense. When would $response->redirect(); get used then?

**Comment by incarnate** [comment]
`$response->redirect()` would only be used with the Responsive Shared Page (`RapidSharedGateway`) in Omnipay. 

Looking at how Omnipay uses `redirect()` in [`getRedirectResponse()`](https://github.com/thephpleague/omnipay-common/blob/master/src/Omnipay/Common/Message/AbstractResponse.php#L176), maybe we should be marking `isRedirect()` as `false` for Transparent Redirect. While it is a "redirect" payment method, it isn't in the sense being used here.

**Comment by delatbabel** [comment]
I need the tests passing please before I can merge.

**Comment by incarnate** [comment]
Hi @delatbabel - I'd say this PR can be closed, the change isn't required. 
We could debate the correctness of `isRedirect()` used for Transparent Redirect but this isn't the best place and there would be backwards compatibility implications.

**Pull request closed without merging**
